### ISSUE TITLE
util.inspect is your friend with this API

### ISSUE THREAD

**Issue by mattcollier** [RedisGraph/redisgraph.js#12]
All the tests and readme show properties being already embedded in strings.  If you already have a json object you want to use, use `util.inspect` as shown below.  Perhaps an example of this can find its way into the readme and/or test suite if others find it useful.
```
api.addEvent = async ({event}) => {
  const query = `CREATE (:event${util.inspect(event)})`;
  const result = await graph.query(query);
  console.log('RESULT', result);
};
```
Not sure yet how to deal with quoted object key values required for keys like 'some-key' or '@context' in javascript.  Also, it appears that nested properties are not allowed.  I'm not sure yet if that's a Cypher limitation or a limitation somewhere in the RedisGraph stack.

**Comment by Sceat** [comment]
nested props are a cypher limitation, not sure if it's too encourage peoples to follow a graph way of creating nodes instead of nesting objects or if it's just the neo4j team being lazy
