### ISSUE TITLE
problem with multi node count

### ISSUE THREAD

**Issue by renewooller** [RedisGraph/redisgraph.js#29]
Hi, 
if you set up three nodes of two different types and try count them:

```
graph.query "test" "CREATE (a:a {aid : 1}),(b:b {bid:1})"
graph.query "test" "CREATE (a:a {aid : 2}),(b:b {bid:2})"
graph.query "test" "CREATE (a:a {aid : 3}),(b:b {bid:3})"
graph.query "test" "MATCH (a:a), (b:b) RETURN count(a) as counta, count(b) as countb"

```
you'll notice that the count is squared of what it should be, it 9 instead of 3. 

Cheers,
Rene

**Comment by DvirDukhan** [comment]
hi @renewooller 
this is redisgraph issue, please open it at https://github.com/RedisGraph/RedisGraph/issues

**Comment by swilly22** [comment]
Same behavior as Neo4j, in this case you should use `count(distinct a), count(distinct b)`
