### ISSUE TITLE
Typescript typings please

### ISSUE THREAD

**Issue by davidLeonardi** [RedisGraph/redisgraph.js#5]
Congrats on this fantastic project.
Could the maintainer/s please provide Typescript typings to the definitelyTyped project so this can be used with TS as well?

Thanks!

**Comment by DenisCarriere** [comment]
Refactored the entire codebase to Typescript via PR https://github.com/RedisGraph/redisgraph.js/pull/10

**Comment by jasperblues** [comment]
@DenisCarriere If you like typescript, perhaps you would like to try DRIVINE.ORG. 

I'm currently adding RedisGraph support. One aspect that will improve the general utility is the transaction support (details on the website). Examples currently use NestJS - will dd some without that framework soon.
