### ISSUE TITLE
graph.query wont escape params

### ISSUE THREAD

**Issue by avifatal** [RedisGraph/redisgraph.js#51]
Hi,
From my experience, query bindings capabilities escape the data before it is being saved to the database. for security reasons and data integrity reasons...

```await graph.query("CREATE (n:Person { name: $name })", {name: 'test"abc'});```

This will throw an error:

``` 
ReplyError: errMsg: Invalid input 'a': expected ';', a statement option, a query hint, a clause or a schema command line: 1, column: 1, offset: 0 errCtx: abc"  CREATE (n:Person { name: $name }) errCtxOffset: 0
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
```

I think it must be escaped by the framework...

Thanks

**Comment by DvirDukhan** [comment]
@avifatal 
please verify so I can close this issue

**Comment by avifatal** [comment]
@DvirDukhan Thanks for the fast reply. I was a little bit off. will have a soon. thanks

**Comment by avifatal** [comment]
Verified

**Comment by avifatal** [comment]
@DvirDukhan Hi,
When are you going to release it here https://www.npmjs.com/package/redisgraph.js ?
Thanks

**Comment by DvirDukhan** [comment]
@avifatal 
this week

**Comment by DvirDukhan** [comment]
@avifatal published

**Comment by avifatal** [comment]
Toda!

**Comment by DvirDukhan** [comment]
Bevakasha
I think you should wait for 2.2.1
https://github.com/RedisGraph/redisgraph.js/pull/56
I missed an edge case
