### ISSUE TITLE
Console Warning: "unable to retrive label value for label index -2"

### ISSUE THREAD

**Issue by FlorianPfisterer** [RedisGraph/redisgraph.js#57]
While running my test suite, I'm getting a lot of the following console warnings *about one in two times I run it*.
```
unable to retrive label value for label index -2
```

The number of times this is printed to the console per test suite run varies too, from 2-3 times up to about 30 times.
It is printed to the console from the following query:
```javascript
const id = 'some-node-id';
const result = await this.graph.query(`MATCH (n:user)`
    + ` WHERE n.id = '${id}'`
    + ` RETURN n`
);
```

Despite the warning, the code performs as intended and the node includes all expected properties.

I have looked into the code, specifically into [`src/resultSet.js`](https://github.com/RedisGraph/redisgraph.js/blob/master/src/resultSet.js#L182) where this is printed. If I increase the maximum `tries` for getting a label to 20 (from 10) [here](https://github.com/RedisGraph/redisgraph.js/blob/master/src/resultSet.js#L176) in the while loop condition, it seems to happen less, but still in at least once in about one of two test suite runs.
This is happening since I have added some more edge and node labels. I now have up to 3 node and up to 3 edge properties.

Is this a bug of the framework? Or am I doing something wrong here? And why does the warning occur only sometimes? (I'm running `.deleteGraph()` after each test). Can someone give me some insight what the 10 tries of getting the label mean and why they're necessary?
Thank you!

**Comment by DvirDukhan** [comment]
hi @FlorianPfisterer 
Can you specify your RedisGraph version?
`-2` for index values is an indication from RedisGraph that it encountered an unknown label. We issued a fix for it before at https://github.com/RedisGraph/RedisGraph/pull/1358, so we would like to know if it is a new issue on our newer versions or just an old RedisGraph version.
Thanks

**Comment by FlorianPfisterer** [comment]
Hi @DvirDukhan,

thanks for the fast reply! I'm just using the Docker image you provide (i.e., running `docker run -p 6379:6379 -it --rm redislabs/redisgraph`). I'm not 100% sure which version this uses by default. 

So I tried again using `:latest`, which resulted in the same console warnings.
I also ran `MODULE LIST` in the Redis CLI, which gave me `20208` -- perhaps that represents 2.2.8.

**Comment by DvirDukhan** [comment]
Thanks we will check it

**Comment by DvirDukhan** [comment]
@FlorianPfisterer 
Can you perhaps provide reproduction steps regarding the graph building?

**Comment by FlorianPfisterer** [comment]
@DvirDukhan that's a bit difficult, since it's integrated into a large project. Will try to reproduce it in a separate setup.

**Comment by FlorianPfisterer** [comment]
Alright, while trying to isolate the problem, I uncovered the true problem -- which is not related to RedisGraph:
I was inserting a large test dataset into the graph, forgetting to `await` the Promise that inserted the data. Then, when the test was already completed (which it apparently could do without the full dataset loaded into the graph) and deleted the graph as part of the teardown, this promise was still inserting data into the graph in the background.
This also explains why it was only happening sometimes and in varying numbers.

Once I `await`ed the Promise that filled the test graph, it all worked fine.
Thanks for your help and thanks for this great library / Redis module!
