### ISSUE TITLE
“require is not defined” : how to be able to use "import" and / or use "require"?

### ISSUE THREAD

**Issue by raphael10-collab** [RedisGraph/redisgraph.js#73]
Following this example: https://github.com/RedisGraph/redisgraph.js/blob/master/examples/redisGraphExample.ts I tried to include redisgraph in my Electron-Typescript-React-Webpack app with `const RedisGraph = require("redisgraph.js").Graph;` in the react page but got `require is not defined`.  

This is my `tsconfig.json` : 

    {
      "compilerOptions": {
        "target": "esnext",
        "module": "commonjs",
        "lib": ["dom", "es2015", "esnext"],
        "outDir": "dist",
        "jsx": "react",
        "baseUrl": "./src",
        "paths": {
          "@sections/*": ["app/sections/*"],
          "@app/*": ["app/*"]
        },
        "strict": true,
        "sourceMap": true,
        "skipLibCheck": true,
        "noImplicitAny": false,
        "noImplicitThis": false,
        "moduleResolution": "node",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "resolveJsonModule": true,
        "allowJs": true
      },
      "include": ["src/**/*"],
      "exclude": [
        "src/index.js",
        "dist",
      ]
    }

I've put in `type.d.ts`  :

    declare module RedisGraph {
      require("redisgraph.js").Graph
    }

But this is not sufficient and/or ok. 

How to make `require` available in the react page, or how to use `import` for this module ?

**Comment by leibale** [comment]
`import { Graph } from 'redisgraph.js'` should do the trick

**Comment by raphael10-collab** [comment]
Hi @leibale ! 
Thanks for helping.

If I put 

    import { Graph } from 'redisgraph.js';
    let graph = new Graph("notes");

I get the error message `require is not defined`

**Comment by leibale** [comment]
please take a look at https://www.electronjs.org/docs/tutorial/quick-start#nodejs-api

**Comment by raphael10-collab** [comment]
I get the error `require is not defined` in runtime.

https://www.electronjs.org/docs/tutorial/quick-start#nodejs-api : this is what I've done:
I installed redisgraph.js with `yarn add github:RedisGraph/redisgraph.js.git` 
and then required the module

    const RedisGraph = require("redisgraph.js").Graph;

But I get at the runtime: `require is not defined`
![image](https://user-images.githubusercontent.com/70313067/117173026-a5b57b80-adcc-11eb-8261-3468e5f101b4.png)

I tried to do with resisgraph.js what I've done with sqlite3 in `webpack.config.js` :  

    const sqlite3 = require('sqlite3');
    const RedisGraph = require("redisgraph.js").Graph;

        externals: [
          {
            'utf-8-validate': 'commonjs utf-8-validate',
            bufferutil: 'commonjs bufferutil',
          },
          {
            'sqlite3': sqlite3,
          },
          {
            'RedisGraph': RedisGraph,
          }
        ],

But when I start the app I get this error:


    yarn start
    yarn run v1.22.5
    $ yarn run build && electron ./dist/main/main.js
    $ npx webpack --config ./webpack.config.js
    [webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the 
    API schema.
     - configuration[1].externals should be one of these:
       [RegExp | string | object { byLayer?, <key>: [non-empty string, ...] | boolean | string | object { … } } | function, ...] | RegExp | 
    string | object { byLayer?, <key>: [non-empty string, ...] | boolean | string | object { … } } | function
       -> Specify dependencies that shouldn't be resolved by webpack, but should become dependencies of the resulting bundle.     
    The kind of the dependency depends on `output.libraryTarget`.
       Details:
        * configuration[1].externals[2]['RedisGraph'] should be one of these:
          [non-empty string, ...] | boolean | string | object { … }
          -> The dependency used for the external.
          Details:
           * configuration[1].externals[2]['RedisGraph'] should be an array:
             [non-empty string, ...]
           * configuration[1].externals[2]['RedisGraph'] should be a boolean.
             -> `true`: The dependency name is used as target of the external.
           * configuration[1].externals[2]['RedisGraph'] should be a string.
             -> The target of the external.
           * configuration[1].externals[2]['RedisGraph'] should be an object:
             object { … }

**Comment by raphael10-collab** [comment]
But if I require in the main process : 

    const RedisGraph = require("redisgraph.js").Graph;
    let graph = new RedisGraph("notes");

I get this new error:

![image](https://user-images.githubusercontent.com/70313067/117177614-85d48680-add1-11eb-951a-3ca8d1f5c862.png)

**Comment by raphael10-collab** [comment]
Thank you @leibale for your kind help
I close the issue, since now the problems I'm facing seem to be related to the connection to Redis
