### ISSUE TITLE
Handle disconnections.

### ISSUE THREAD

**Issue by chainhead** [RedisGraph/redisgraph.js#74]
1. Is there a `graph.on('disconnect')` event that can be handled if the client loses connection with `RedisGraph` for any reason?
2. Also, is there an option to pool connections?

**Comment by leibale** [comment]
1. you can either provide a client to the constructor (https://redisgraph.github.io/redisgraph.js/Graph.html) or use `graph_client.on('error')`.
2. Redis is "single-threaded" (it's not actually single-threaded, but only one thread is handling the commands), so using a connection pool with Redis will not improve bandwidth/performance in most cases.

**Comment by chainhead** [comment]
On the response to the second point, I have the following.

1. [Connection Pools for Serverless Functions and Backend Services](https://redislabs.com/blog/connection-pools-for-serverless-functions-and-backend-services/) which has a Python application using [`aio-redis`](https://github.com/aio-libs/aioredis) for connection pooling.
2. While the article above also mentions the following, there is an `npm` package [`node-redis-connection-pool`](https://www.npmjs.com/package/redis-connection-pool) too.

> In the case of JavaScript, the client doesn’t offer a connection pool because of the single-threaded nature of Node.js. 

So, I am not sure, what to conclude w.r.t. connection pooling with RedisGraph.
